@startuml Booking system class diagram

abstract class person {
  name: String
  age: int
  gender: String
  personNumber: String
  address: String
  phoneNumber: String
  email: String
  bloodType: String
  emergencyContacts: List<Person>
  maritalStatus: String
  getperson(): person
}

class Patient extends person {
  appointments: List<appointment>
  medicalRecord: List<Object>
  getAppointments(): List<appointment>
  getMedicalRecord(): List<Object>
}

class Doctor extends person {
  appointments: List<appointment>
}

class Appointment {
  patient: Patient
  doctor: Doctor
  date: Date
  time: Time
  note: String
}

class Hospital {
  appointments: List<appointment>
  doctors: List<Doctor>
  patients: List<Patient>
  rooms: List<String>
  name: String
}

class BookingSystem {
  hospitals: List<Hospital>
  patients: List<Patient>
  doctors: List<Doctor>
  appointments: List<appointment>
  getHospitals(): List<Hospital>
  getRooms(): List<Room>
  getPatients(): List<Patient>
  getDoctors(): List<Doctor>
  getAppointments(): List<appointment>
  setAppointments(appointments: List<appointment>): void
}

class Room {
  roomNumber: int
  roomType: String
  getRoomNumber(): int
  setRoomNumber(roomNumber: int): void
  getRoomType(): String
  setRoomType(roomType: String): void
  getAppointment(): List<appointment>
  setAppointment(appointment: appointment): void
}

Hospital "1" -- "..*" Room
Hospital "1" -- "..*" Doctor
Hospital -- "..*" Patient
Patient "1" -- "..*" Appointment
Doctor -- "..*" Appointment
Room "1" -- "..*" Appointment
Hospital -- BookingSystem
BookingSystem -- "..*" Appointment

@enduml
